import type { LtmNote } from "../../../../shared/src/features/agents/long-term-memory/schema.js";
import { compileEvidenceUnitExtraction, runLongTermMemoryEvidenceUnitExtraction } from "./evidence-unit-extraction.js";
import { getLtmExtractionConfig } from "./extraction-config.js";
import { mapGameJournalToEvidenceUnits, computeGameSourceHash, renderGameSourceText } from "./game-journal-mapper.js";
import { nowIso } from "./ltm-utils.js";
import { getPackageLanguageModels, getPackagePersistence, logger } from "./package-runtime.js";
import { resolveScopedEvidenceUnitTargets } from "./scoped-targets.js";
import { LongTermMemoryStorage } from "./storage.js";
import { resolveChatLtmScope } from "./chat-scope.js";

function object(value:unknown):Record<string,unknown>{if(value&&typeof value==="object"&&!Array.isArray(value))return value as Record<string,unknown>;if(typeof value==="string")try{return object(JSON.parse(value));}catch{}return{};}
function throwIfAborted(signal?:AbortSignal){if(!signal?.aborted)return;const error=new Error("Long-term memory import was cancelled.");error.name="AbortError";throw error;}
function provider(resolved:any){return{name:resolved.name,maxContext:resolved.maxContext,maxOutputTokens:resolved.maxOutputTokens,complete:(messages:any,options:any)=>resolved.chatComplete(messages,options),fitContext:(messages:any,options:any)=>resolved.fitContext(messages,options)};}

export async function prepareGameJournalIngest(sourceNote:LtmNote,root?:string,options:{signal?:AbortSignal;operationId?:string;provider?:unknown;model?:string}={}){
  throwIfAborted(options.signal);
  const chatId=sourceNote.scope.chatId??sourceNote.scope.chatIds?.[0];if(!chatId)throw new Error("Cannot direct-ingest game journal: source note has no chatId in scope");
  const chat=await getPackagePersistence().getChat(chatId);if(!chat)throw new Error(`Chat not found: ${chatId}`);
  const metadata=object(chat.metadata),journal=metadata.gameJournal??null,summaries=Array.isArray(metadata.gamePreviousSessionSummaries)?metadata.gamePreviousSessionSummaries:[];
  if(!journal&&!summaries.length)return{sourceNote,extractionMode:"game" as const,response:{summary:"",mutations:[]},diagnostics:[],outcome:{state:"no_suggestions_created" as const,totalCandidates:0,keptUnits:0,droppedUnits:0,droppedCandidates:[]},accounting:{providerCandidates:0,normalizedAdditions:0,parserRejections:0,validationRejections:0,deduplications:0,keptUnits:0},draftless:true as const};
  const sourceText=renderGameSourceText(journal,summaries),sourceHash=computeGameSourceHash(journal,summaries),storage=new LongTermMemoryStorage(root),scope=resolveChatLtmScope(chat),evidence=[`chat:${chatId}`,"game_journal",`game_source_hash:${sourceHash}`],tags=Array.from(new Set([...sourceNote.tags,"source_summary","imported_game_journal"]));
  const currentSource=await storage.updateNote(sourceNote.id,{scope,modes:["game"],tags,provenance:{kind:"game_journal",sourceId:chatId},sections:{...sourceNote.sections,source:{...(sourceNote.sections.source??{}),text:sourceText||sourceNote.sections.source?.text||"Game journal has no durable entries.",updatedAt:nowIso(),confidence:sourceNote.sections.source?.confidence??0.8,evidence}}});
  throwIfAborted(options.signal);
  const units=mapGameJournalToEvidenceUnits(journal,summaries,{chatId,scope,sourceHash}).map((item)=>item.evidence.includes(`source_note:${currentSource.id}`)?item:{...item,evidence:[...item.evidence,`source_note:${currentSource.id}`]}),existing=(await storage.listNotes({scope,includeGlobal:true})).filter((note)=>note.type!=="source"&&note.type!=="scene"),targets=await resolveScopedEvidenceUnitTargets({storage,existingNotes:existing,units,scope}),summary=`Direct ingestion of game journal + ${summaries.length} session summaries`;
  const structural=compileEvidenceUnitExtraction({unitResponse:{summary,units:targets.units},totalCandidates:units.length,sourceText,sourceNote:currentSource,existingNotes:targets.existingNotes,scope,modes:["game"],mode:"game",sourceHash});
  let response=structural.compiledResponse,diagnostics=[...structural.diagnostics,...targets.diagnostics],outcome=structural.outcome,accounting=structural.accounting;
  const config=await getLtmExtractionConfig(root,"game"),refinePass=metadata.refinePass===true||config.refinePass===true;
  if(refinePass)try{throwIfAborted(options.signal);const resolved=await getPackageLanguageModels().resolveForRequest({chatConnectionId:chat.connectionId}),refined=await runLongTermMemoryEvidenceUnitExtraction({sourceNote:currentSource,sourceText,existingNotes:existing,candidateUnits:units,provider:provider(resolved),model:resolved.model,root,scope,modes:["game"],sourceHash,systemPrompt:config.systemPrompt,reasoningEffort:config.reasoningEffort,verbosity:config.verbosity,maxOutputTokens:config.maxOutputTokens,temperature:config.temperature,maxExistingNoteTokens:config.maxExistingNoteTokens,operationId:options.operationId,mode:"game",aiKeywordExtraction:config.aiKeywordExtraction,refinePass:true,resolveSubjectNames:false,signal:options.signal}),refinedTargets=await resolveScopedEvidenceUnitTargets({storage,existingNotes:existing,units:refined.response.units,scope}),compiled=compileEvidenceUnitExtraction({unitResponse:{...refined.response,units:refinedTargets.units},totalCandidates:refined.totalCandidates,parserDroppedCandidates:refined.droppedCandidates,sourceText,sourceNote:currentSource,existingNotes:refinedTargets.existingNotes,scope,modes:["game"],mode:"game",sourceHash});if(compiled.compiledResponse.mutations.length){response=compiled.compiledResponse;diagnostics=[...compiled.diagnostics,...refinedTargets.diagnostics];outcome=compiled.outcome;accounting=compiled.accounting;}}catch(error){if(options.signal?.aborted||(error instanceof Error&&error.name==="AbortError"))throw error;logger.warn(error,"[ltm] Game journal refine pass failed; using structural ingestion for %s",chatId);}
  return{sourceNote:currentSource,extractionMode:"game" as const,response,diagnostics,outcome,accounting,draftless:false as const};
}
