import { DEFAULT_LTM_EXTRACTION_EXISTING_NOTE_MAX_CHUNKS, DEFAULT_LTM_EXTRACTION_EXISTING_NOTE_MAX_TOKENS, DEFAULT_LTM_EXTRACTION_MAX_EXISTING_NOTE_TOKENS, DEFAULT_LTM_EXTRACTION_MAX_SOURCE_TOKENS, DEFAULT_LTM_EXTRACTION_MAX_TOKENS, DEFAULT_LTM_EXTRACTION_PROMPT, DEFAULT_LTM_EXTRACTION_REASONING_EFFORT, DEFAULT_LTM_EXTRACTION_TEMPERATURE, DEFAULT_LTM_EXTRACTION_VERBOSITY } from "../../../../shared/src/features/agents/long-term-memory/constants.js";
import { ltmExtractionSettingsSchema, ltmResolvedExtractionSettingsSchema } from "../../../../shared/src/features/agents/long-term-memory/schema.js";
import { readJsonFile, writeJsonAtomic } from "./atomic-json.js";
import { getLongTermMemoryDirectories, getLongTermMemoryRoot, safeJoin } from "./paths.js";
import { withLtmVaultLock } from "./vault-lock.js";
export const DEFAULT_LTM_EXTRACTION_CONFIG = ltmResolvedExtractionSettingsSchema.parse({ version: 1, systemPrompt: DEFAULT_LTM_EXTRACTION_PROMPT, reasoningEffort: DEFAULT_LTM_EXTRACTION_REASONING_EFFORT, verbosity: DEFAULT_LTM_EXTRACTION_VERBOSITY, maxOutputTokens: DEFAULT_LTM_EXTRACTION_MAX_TOKENS, temperature: DEFAULT_LTM_EXTRACTION_TEMPERATURE, maxSourceTokens: DEFAULT_LTM_EXTRACTION_MAX_SOURCE_TOKENS, maxExistingNoteTokens: DEFAULT_LTM_EXTRACTION_MAX_EXISTING_NOTE_TOKENS, existingNoteMaxChunks: DEFAULT_LTM_EXTRACTION_EXISTING_NOTE_MAX_CHUNKS, existingNoteMaxTokens: DEFAULT_LTM_EXTRACTION_EXISTING_NOTE_MAX_TOKENS, promptTemplates: [], activePromptTemplateId: null, activePromptTemplateIdsByMode: {}, aiKeywordExtraction: false, refinePass: false });
export const ltmExtractionConfigPath = (root = getLongTermMemoryRoot()) => safeJoin(getLongTermMemoryDirectories(root).config, "extraction.json");
export async function getLtmExtractionConfig(root = getLongTermMemoryRoot()) { const parsed = ltmExtractionSettingsSchema.parse(await readJsonFile<unknown>(ltmExtractionConfigPath(root), { version: 1 })); return ltmResolvedExtractionSettingsSchema.parse({ ...DEFAULT_LTM_EXTRACTION_CONFIG, ...parsed, version: 1 }); }
export async function updateLtmExtractionConfig(input: unknown, root = getLongTermMemoryRoot()) { return withLtmVaultLock(root, async () => { const parsed = ltmExtractionSettingsSchema.parse(input ?? {}); await writeJsonAtomic(ltmExtractionConfigPath(root), parsed); return getLtmExtractionConfig(root); }); }
