import assert from "node:assert/strict";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

async function main() {
  const engineRoot=process.env.MARINARA_ENGINE_ROOT??process.cwd();
  const Fastify=(await import(pathToFileURL(join(engineRoot,"packages/server/node_modules/fastify/fastify.js")).href)).default;
  const {registerCapabilityPrivilegedRoutes}=await import(pathToFileURL(join(engineRoot,"packages/server/src/services/capability-packages/capability-route-registration.service.ts")).href);
  const {activate}=await import("../packages/long-term-memory/src/engine/packages/server/src/services/long-term-memory/server-entry.ts");
  const app=Fastify();
  const dataDir=await mkdtemp(join(tmpdir(),"marinara-ltm-routes-"));
  const installed={id:"long-term-memory",version:"1.0.0",installedAt:"2026-07-17T00:00:00.000Z",status:"active",error:null,readiness:"pending",readinessError:null,legacy:false,manifest:{schemaVersion:2,capabilityApi:{major:1,minor:4},builtAgainst:{engineVersion:"2.3.2",engineCommit:"a".repeat(40)},id:"long-term-memory",name:"Long-Term Memory",version:"1.0.0",description:"fixture",engine:{min:"2.3.2",maxExclusive:"2.4.0"},kind:["agent"],entrypoints:{server:"server.mjs",agents:"agents.json"},files:[{path:"server.mjs",sha256:"0".repeat(64),bytes:1}],permissions:["agent-runtime","chat-read","routes","storage"],restartRequired:true}};
  const previousSecret=process.env.ADMIN_SECRET;
  const previousRequireSecret=process.env.MARINARA_REQUIRE_ADMIN_SECRET_ON_LOOPBACK;
  process.env.ADMIN_SECRET="ltm-route-secret";
  process.env.MARINARA_REQUIRE_ADMIN_SECRET_ON_LOOPBACK="true";
  let cleanup:(()=>void|Promise<void>)|undefined;
  let storageService:any;
  let modelCalls=0;
  const modelRequests:any[]=[];
  const completionOptions:any[]=[];
  const debugOverrides:any[]=[];
  try{
    assert.deepEqual(installed.manifest.permissions,["agent-runtime","chat-read","routes","storage"]);
    assert.equal(installed.manifest.permissions.includes("network"),false);
    await assert.rejects(registerCapabilityPrivilegedRoutes(app,{...installed,manifest:{...installed.manifest,permissions:installed.manifest.permissions.filter((permission)=>permission!=="routes")}} as any,async()=>{}, {prefix:"/api/permission-fixture"}),/must declare the routes permission/);
    const chats=["chat-a","chat-b"].map((id)=>({id,mode:"roleplay",characterIds:["character-mara"],groupId:null,personaId:null,connectionId:"connection-a",metadata:{}}));
    cleanup=await activate({dataDir,api:{runtime:{isDebugAgentsEnabled(){return true;},logger:{debug(){},info(){},warn(){},error(){},debugOverride(enabled:boolean,message:string,...args:any[]){debugOverrides.push({enabled,message,args});}},languageModels:{async resolveForRequest(request:any){modelRequests.push(request);if(request.model==="missing-model")throw new Error("Language model connection not found: connection-a");return{name:"FixtureModel",connectionId:request.connectionId??"connection-a",model:request.model??"fixture-model",maxContext:32_000,maxOutputTokens:4_000,async chatComplete(_messages:any[],options:any){modelCalls+=1;completionOptions.push(options);return{content:JSON.stringify({summary:"Extracted observatory facts.",units:[{bucket:"world_fact",subjectId:"observatory_gate",sectionKey:"facts",text:"The observatory gate is sealed at dusk.",importance:"major",evidence:["source_note:source_route_extract"],confidence:0.95,salience:0.9,status:"active",links:[],sourceHash:"replaced-by-package"},{bucket:"character_fact",subjectId:"mara",subjectNames:["Mara"],sectionKey:"role",text:"Mara seals the observatory gate at dusk.",importance:"major",evidence:["source_note:source_route_extract"],confidence:0.95,salience:0.9,status:"active",links:[],sourceHash:"replaced-by-package"}]}),finishReason:"stop",usage:{promptTokens:100,completionTokens:50,totalTokens:150}};},fitContext(messages:any[],options:any){return{messages,maxTokens:options.maxTokens,estimatedTokensBefore:100,estimatedTokensAfter:100,trimmed:false};}};}},resources:{async listCharacters(){return[{id:"character-mara",data:{name:"Mara"},comment:""}];},async listPersonas(){return[];}},persistence:{async getChat(chatId:string){return chats.find((chat)=>chat.id===chatId)??null;},async listChats(){return chats;}}},registerService(name:string,service:unknown){if(name==="long-term-memory:storage")storageService=service;return()=>void service||void name;},registerPrivilegedRoutes:(routes:any,options:{prefix:string})=>registerCapabilityPrivilegedRoutes(app,installed as any,routes,options)}});
    await app.ready();
    assert.equal((await app.inject({method:"GET",url:"/api/long-term-memory/settings"})).statusCode,403);
    const headers={"x-admin-secret":"ltm-route-secret"};
    assert.equal((await app.inject({method:"GET",url:"/api/long-term-memory/settings",headers})).statusCode,200);
    assert.equal((await app.inject({method:"GET",url:"/api/long-term-memory/status",headers})).statusCode,200);
    const created=await app.inject({method:"POST",url:"/api/long-term-memory/notes",headers,payload:{id:"world_route_fixture",title:"Route fixture",type:"world",status:"active",modes:["roleplay"],scope:{chatId:"chat-a",chatIds:["chat-a"]},tags:["route_fixture"],keywords:["cobalt"],links:[],sections:{facts:{text:"The cobalt key is beneath the observatory.",updatedAt:"2026-07-17T00:00:00.000Z"}}}});
    assert.equal(created.statusCode,201,created.body);
    const notSource=await app.inject({method:"POST",url:"/api/long-term-memory/notes/world_route_fixture/extract",headers,payload:{}});
    assert.equal(notSource.statusCode,400,notSource.body);
    const concurrent=await Promise.all([1,2].map(()=>app.inject({method:"POST",url:"/api/long-term-memory/notes",headers,payload:{id:"world_concurrent_fixture",type:"world",status:"active",modes:["roleplay"],scope:{},tags:[],keywords:[],links:[],sections:{facts:{text:"Only one create may commit.",updatedAt:"2026-07-17T00:00:00.000Z"}}}})));
    assert.deepEqual(concurrent.map((response)=>response.statusCode).sort(),[201,409]);
    const listed=await app.inject({method:"GET",url:"/api/long-term-memory/notes?scopeChatIds=chat-a&includeGlobal=false",headers});
    assert.deepEqual(listed.json().map((note:any)=>note.id),["world_route_fixture"]);
    const searched=await app.inject({method:"POST",url:"/api/long-term-memory/search",headers,payload:{queryText:"cobalt observatory",scope:{chatId:"chat-a",chatIds:["chat-a"]}}});
    assert.equal(searched.statusCode,200,searched.body);
    assert.equal(searched.json().chunks[0]?.chunk.noteId,"world_route_fixture");
    const transfer=await app.inject({method:"POST",url:"/api/long-term-memory/notes/transfer",headers,payload:{noteIds:["world_route_fixture"],mode:"copy",destinationChatId:"chat-b"}});
    assert.equal(transfer.statusCode,200,transfer.body);
    assert.deepEqual(transfer.json().updatedNoteIds,["world_route_fixture"]);
    const extractSource=await app.inject({method:"POST",url:"/api/long-term-memory/notes",headers,payload:{id:"source_route_extract",title:"Observatory report",type:"source",status:"active",modes:["roleplay"],scope:{chatId:"chat-a",chatIds:["chat-a"]},tags:["source_summary"],keywords:[],links:[],sections:{source:{text:"Mara seals the observatory gate at dusk.",updatedAt:"2026-07-17T00:00:00.000Z"}}}});
    assert.equal(extractSource.statusCode,201,extractSource.body);
    const invalidMode=await app.inject({method:"POST",url:"/api/long-term-memory/notes/source_route_extract/extract",headers,payload:{chatId:"chat-a",mode:"conversation"}});
    assert.equal(invalidMode.statusCode,400,invalidMode.body);
    assert.match(invalidMode.json().error,/mode is not enabled/);
    const missingModel=await app.inject({method:"POST",url:"/api/long-term-memory/notes/source_route_extract/extract",headers,payload:{chatId:"chat-a",model:"missing-model"}});
    assert.equal(missingModel.statusCode,400,missingModel.body);
    const extracted=await app.inject({method:"POST",url:"/api/long-term-memory/notes/source_route_extract/extract",headers,payload:{chatId:"chat-a",connectionId:"request-connection",model:"request-model"}});
    assert.equal(extracted.statusCode,200,extracted.body);
    assert.deepEqual(extracted.json().draft?.mutations.map((mutation:any)=>mutation.note?.id).sort(),["char_mara","world_observatory_gate"]);
    assert.deepEqual(extracted.json().draft?.mutations.find((mutation:any)=>mutation.note?.id==="char_mara")?.note.subjects,[{key:"character:character-mara",ref:{kind:"character",id:"character-mara"}}]);
    assert.deepEqual(modelRequests.at(-1),{connectionId:"request-connection",chatConnectionId:"connection-a",model:"request-model"});
    assert.equal(completionOptions.at(-1)?.debugMode,true);
    assert.equal(completionOptions.at(-1)?.maxTokens,4_000);
    assert.equal(completionOptions.at(-1)?.temperature,0);
    assert.equal(completionOptions.at(-1)?.reasoningEffort,"low");
    assert.equal(completionOptions.at(-1)?.verbosity,"low");
    assert.equal(completionOptions.at(-1)?.responseFormat?.type,"json_schema");
    assert.equal(debugOverrides.some((entry)=>entry.enabled&&entry.message.includes("extraction prompt")),true);
    const chatDrafts=await app.inject({method:"GET",url:"/api/long-term-memory/drafts?chatId=chat-a",headers});
    assert.equal(chatDrafts.statusCode,200,chatDrafts.body);
    assert.equal(chatDrafts.json().some((draft:any)=>draft.id===extracted.json().draft.id),true);
    assert.equal((await app.inject({method:"GET",url:"/api/long-term-memory/drafts/pending-count?chatId=chat-a",headers})).json().count,1);
    assert.equal(modelCalls,1);
    const autoApplied=await app.inject({method:"POST",url:"/api/long-term-memory/notes/source_route_extract/extract",headers,payload:{chatId:"chat-a",applyLowRisk:true}});
    assert.equal(autoApplied.statusCode,200,autoApplied.body);
    assert.equal(autoApplied.json().appliedMutationIds.length>0,true);
    assert.equal(autoApplied.json().draft.indexRebuildStatus,"not_requested");
    assert.equal(modelCalls,2);
    const gameSource=await app.inject({method:"POST",url:"/api/long-term-memory/notes",headers,payload:{id:"source_route_game",title:"Game journal",type:"source",status:"active",modes:["game"],scope:{},tags:["source_summary","imported_game_journal"],keywords:[],links:[],sections:{source:{text:"A game journal entry.",updatedAt:"2026-07-17T00:00:00.000Z"}}}});
    assert.equal(gameSource.statusCode,201,gameSource.body);
    const gameExtract=await app.inject({method:"POST",url:"/api/long-term-memory/notes/source_route_game/extract",headers,payload:{}});
    assert.equal(gameExtract.statusCode,400,gameExtract.body);
    assert.match(gameExtract.json().error,/Game journal extraction is not supported/);
    assert.equal(modelCalls,2);
    const source=await app.inject({method:"POST",url:"/api/long-term-memory/notes",headers,payload:{id:"source_route_review",title:"Draft source",type:"source",status:"active",modes:["roleplay"],scope:{chatId:"chat-a",chatIds:["chat-a"]},tags:["source_summary"],keywords:[],links:[],sections:{source:{text:"The eastern gate is sealed at dusk.",updatedAt:"2026-07-17T00:00:00.000Z"}}}});
    assert.equal(source.statusCode,201,source.body);
    await writeFile(join(storageService.root,"drafts","malformed.json"),"{not-json","utf8");
    const mutationId="10000000-0000-4000-8000-000000000001";
    const mutation={id:mutationId,kind:"create_note",risk:"low",confidence:0.9,summary:"Create gate fact",evidence:["The eastern gate is sealed at dusk."],note:{id:"world_eastern_gate",title:"Eastern gate",type:"world",status:"active",modes:["roleplay"],scope:{chatId:"chat-a",chatIds:["chat-a"]},tags:[],keywords:["gate","dusk"],links:[],sections:{facts:{text:"The eastern gate is sealed at dusk.",updatedAt:"2026-07-17T00:00:00.000Z"}}}};
    const draft=await storageService.drafts.createDraft({source:{sourceNoteId:"source_route_review",chatId:"chat-a"},scope:{chatId:"chat-a",chatIds:["chat-a"]},modes:["roleplay"],summary:"Remember the gate schedule.",response:{summary:"Remember the gate schedule.",mutations:[mutation]}});
    const review=await app.inject({method:"GET",url:"/api/long-term-memory/drafts/review?sourceNoteId=source_route_review",headers});
    assert.equal(review.statusCode,200,review.body);
    assert.equal(review.json().counts.drafts,1);
    assert.equal(review.json().sources[0]?.drafts[0]?.freshness,"fresh");
    assert.equal(review.json().sources[0]?.targets[0]?.noteId,"world_eastern_gate");
    assert.equal((await app.inject({method:"GET",url:"/api/long-term-memory/drafts",headers})).statusCode,200);
    const accepted=await app.inject({method:"POST",url:`/api/long-term-memory/drafts/${draft.id}/accept`,headers,payload:{mutationIds:[mutationId]}});
    assert.equal(accepted.statusCode,200,accepted.body);
    assert.deepEqual(accepted.json().appliedMutationIds,[mutationId]);
    assert.equal(accepted.json().draft.status,"accepted");
    assert.equal((await storageService.storage.getNote("world_eastern_gate"))?.sections.facts.text,"The eastern gate is sealed at dusk.");
    const integrity=await app.inject({method:"GET",url:"/api/long-term-memory/integrity",headers});
    assert.equal(integrity.statusCode,200,integrity.body);
    assert.equal(integrity.json().ok,true);
    await cleanup();
    cleanup=undefined;
    assert.equal((await app.inject({method:"GET",url:"/api/long-term-memory/settings",headers})).statusCode,404);
  }finally{
    await cleanup?.();
    await app.close();
    await rm(dataDir,{recursive:true,force:true});
    if(previousSecret===undefined)delete process.env.ADMIN_SECRET;else process.env.ADMIN_SECRET=previousSecret;
    if(previousRequireSecret===undefined)delete process.env.MARINARA_REQUIRE_ADMIN_SECRET_ON_LOOPBACK;else process.env.MARINARA_REQUIRE_ADMIN_SECRET_ON_LOOPBACK=previousRequireSecret;
  }
  process.stdout.write("Long-Term Memory routes regression: permissions, malformed drafts, model/debug forwarding, chat draft visibility, client errors, extraction, cleanup ok\n");
}

void main().catch((error)=>{console.error(error);process.exitCode=1;});
